version: '3'
services:
  web:
    build: .
    ports:
     - "8085:80"
    restart: always
    environment:
        BATHROOM_AVAILABILITY_CONF: "/app/app.config"
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: supersecurepassword
        MYSQL_DATABASE: log
